### ISSUE TITLE
Adjustable block width & height

### ISSUE THREAD

**Issue by JohnUCSB** [UCSB-CS56-Projects/cs56-utilities-binary-clock#18] opened 2015-03-12 23:35 UTC
Block width & height are fixed, and the AM/PM block is much narrower than the other blocks. It would be great if we can adjust the block sizes. You will probably need to play with BinaryClock.java and TimePanel.java to fix this bug. You will also need to study how border layout and flow layout work.

Suggested Points: ~200

**Comment by dcoffill** [comment] 2015-03-12 23:42
Approved

**Comment by JohnUCSB** [comment] 2016-10-13 02:08
F16 Approved  - 200 pts

**Comment by jimmylle** [comment] 2016-12-02 00:09
The [pull request](https://github.com/UCSB-CS56-Projects/cs56-utilities-binary-clock/pull/30) referenced above didn't really resolve the issue fully. The reference fixes the size of some of the blocks and now makes them all have the same size but it doesn't really solve the core part of this issue.

**Comment by xavierholt** [comment] 2017-10-02 21:57
Closing for F17 'cause it's not apparent from looking at the GUI what the problem is.  If it's bad code, I'll open a refactor ticket.

**Closed by xavierholt** 2017-10-02 21:57 UTC

**Comment by xavierholt** [comment] 2017-10-03 00:14
This is possibly what I'm referencing in https://github.com/UCSB-CS56-Projects/cs56-utilities-binary-clock/issues/44?
